path: /home/ryanscodingden/IPS images
train: /home/ryan/IPS-DATA/Data/train/images
val: /home/ryan/IPS-DATA/Data/validation/images
test: /home/ryan/IPS-DATA/Data/test/images
nc: 2
names:
- Tree_group
- Tree
